name: CI

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v2
      - run: pnpm lint

  test:
    needs: lint
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version:
          - 18
          - 20
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm test
